### PR TITLE
Add schema to autocompletition

### PR DESCRIPTION
**Pull request by lafriks**
Adds schema autocomplete support and also if schema is found show only tables for that schema in autocomplete.

### CODE REVIEW

**Comment by Borvik** [comment]
Looking through the changes, I noticed the new DBSchema interface only has a name.  Schemas in the query can be double-quoted identifiers as well.  How does that respond?

**Comment by lafriks** [comment]
DBTable etc interfaces does not have quoting information as postgresql won't return such information if it needs to be quoted or not. This handling should be probably improved also for tables and fields in other PR

**Comment by lafriks** [comment]
Also what should probably be handled better in future is about if table is in default search path or not. Currently it does depend on behavior that only `public` schema tables are in search path

**Comment by lafriks** [comment]
@Borvik Anything I can help to get my PRs merged?

**Pull request merged**
