### PR TITLE
Add optional database and schema explorer filter

### PR DESCRIPTION
**Pull request by peterbam**

### CODE REVIEW

**Comment by peterbam** [comment]
Add to user settings overwrite

```
    "vscode-postgres.databaseFilter": [ "db1", "db2" ],
    "vscode-postgres.schemaFilter": [ "schema1", "schema2", "schema3" ]
```

**Comment by Borvik** [comment]
See other pull request for rejection explanation.

**Comment by peterbam** [comment]
Most databases end up with "rubbish" in them, or different schema which you have no access to etc. Agreed this implementation was useless if you had more than one connection. If I rework to work per connection will you accept?

**Comment by Borvik** [comment]
I'm not certain of the "rubbish" you are referring to.

Schema or database with no access to - perhaps the query loading them isn't taking permission into account (perhaps just rework the queries to use permissions).

Depending on the "rubbish", filters might not be necessary as it might get automatically filtered due to the queries (optimal solution).

I would consider accepting if it makes sense, and can work with multiple connections, and prior existing connections (would not require removing and re-adding a connection).

**Comment by Borvik** [comment]
I have found a way to filter based on the current user, and am currently working on a branch for that.
Tree structure will change to Connection > Database > Schema > Table | View
Planned privilege filter on Database, Schemas, Tables and Views.

**Comment by Borvik** [comment]
Ok, so I have an initial implementation on branch schema-node.

There are a few things to clean-up, such as bringing the permission filtering over to intellisense and finding an icon for the Schema objects in the explorer.

You seem familiar with db level permissions (all the database I've used, haven't really needed it), so I'm hoping you'd be willing to test it before it's published.  I've modified permissions locally, but I may have done so differently than an environment that actually uses them.

**Pull request closed without merging**
