### PR TITLE
Add function list display to explorer tree

### PR DESCRIPTION
**Pull request by lafriks**
Has no impact on autocomplete but makes it possible to get list of functions defined under schema in tree view.

attels

Tables are displayed after "virtual" Functions folder:
attels

### CODE REVIEW

**Comment by Borvik** [comment]
Just one concern - the icons.  I've been taking pains to only grab images I can safely use with no attribution required, or ones that I've created myself (with maybe a reference image on another screen).

I just need to know where the icons came from, and if they require an attribution link back to them.

**Comment by lafriks** [comment]
It is simplified version from https://github.com/postgres/pgadmin4/blob/master/web/pgadmin/browser/server_groups/servers/databases/schemas/functions/static/img/coll-function.svg

**Comment by Borvik** [comment]
I merged this, but there is a problem.  It doesn't break existing functionality - but it doesn't allow the `functions` folder to show up.

Namely - the `virtualFolders` configuration setting wasn't added as an available option in `package.json`.

**Comment by lafriks** [comment]
Sorry, had forgotten to commit that file, submitted PR to fix that

**Pull request merged**
