### PR TITLE
Fixes recent "cannot read property of null" errors

### LINKED ISSUE #19: Cannot read property 'metadata' of null
I can still connect and view tables, views, and columns in each. However, when I try to run a query I get:

image

This started after the latest update to vsc.

### PR DESCRIPTION
**Pull request by Yarith**
Fixes #19 and #27.

A short story to explain the steps to solve this issue:
Since vscode 0.14.0 the loading of the modules for the vscode-postgres extension has changed. This caused the recently appearing "cannot read property of null" errors on windows. In the first few minutes of my debugging session i noticed, that a static field is set to a value but later has the value null. In another debugging session i noticed that the module got loaded twice. After 10 minutes i found out the reason.

On the first call the module got loaded from a path with a upper case drive letter. On the second call the module got loaded from a path with a lower case drive letter. The module system uses internally a dictionary with case sensitive keys to find out if the module is already loaded. Of course on the second call the path with the lower case drive letter was not in the dictionary. So it loaded the module the second time.

In the case of duplicate loading of the treeProvider module following happened:
The first module loading was triggered by the import statement in the extension.ts file. So i assumed this was the correct one. The second module was loaded by the command, in my test case by the addConnection-Command. Walking the stack trace up, i noticed that already the addConnection was loaded with a lower case. With a breakpoint on the addConnection module initialization i walked the stack trace up to the activate function in the "extension.ts" file. There i found out that the commandPath, which was set with the help of the ```context.asAbsolutePath``` function, is with a lower case path. Tried to find information about this function with google but without results.

After a break i tried to find a solution for this problem. I noticed, that all modules except the command modules are loaded with a relative path. So i changed the require call in the extension.ts file to a relative file too. Started vscode with my change and tried to add a new connection, which has worked.

I have tested it only on my windows 10 machine. Maybe the solution with the relative path does not work on other systems. But i think there should be no problem, because all other require calls are in the js file with a relative path.

### CODE REVIEW

**Comment by Borvik** [comment]
I was just working on this issue and found the problem - seems we found it almost the same time

**Comment by Yarith** [comment]
Found the reason 10 hours ago and was finished with the fix 2 hours ago. Creating commit, push and pull request took until now. Did not expect you will work on it today. Bad luck.

**Comment by Borvik** [comment]
the other place wasn't really required - but should have been done anyway (just a context specifier for "this" so it might work properly in async command calls - if needed)

**Comment by Borvik** [comment]
thanks for the help though 😄

**Pull request closed without merging**
